kGorgeTunnelCost = 3
kGorgeTunnelCostDigest = 2
kGorgeTunnelCostKill = 0
kGorgeTunnelBuildTime = 12 --18.5
kGorgeWhipCost = 10
kGorgeWhipCostDigest = 6
kGorgeWhipCostKill = 0
kGorgeCragCost = 10
kGorgeCragCostDigest = 6
kGorgeCragCostKill = 0
kGorgeShiftCost = 10
kGorgeShiftCostDigest = 6
kGorgeShiftCostKill = 0
kGorgeShadeCost = 10
kGorgeShadeCostDigest = 6
kGorgeShadeCostKill = 0
kGorgeShadeCloakRadius = 17
kGorgeShadeHealth = 500
kGorgeShadeArmor = 0
kGorgeCragHealth = 320
kGorgeCragArmor = 100
kGorgeShiftHealth = 400
kGorgeShiftArmor = 50
kGorgeWhipHealth = 390
kGorgeWhipArmor = 80
kGorgeWhipBuildTime = 10
kGorgeWhipSlapDamage = 30
--kGorgeStructuresPerHive = 3  --not used yet

-- kGorgeTunnelBuildTime = 18.5
kHydraDamage = 8
kMatureWhipHealth = 950    kMatureWhipArmor = 725